clc
clear
close all

%%=========================================================
% LD3 Cooling Water System Simulation
%==========================================================

run('data.m')

Results = RunSimulation(...
Q_total,...
Q_hood,...
Q_lance,...
Q_ring,...
Cp,...
rho,...
T_supply,...
T_return,...
PumpPressure,...
g,...
eta,...
mu,...
D,...
L,...
f,...
HotIn,...
HotOut,...
U,...
A);

disp(' ')
disp('===========================================')
disp('LD3 COOLING WATER SYSTEM SIMULATION')
disp('===========================================')
disp(Results)

DisplayResults(...
Results.MassFlow,...
Results.HoodFlow,...
Results.LanceFlow,...
Results.RingFlow,...
Results.DeltaT,...
Results.Qtotal,...
Results.PumpHead,...
Results.PumpPowerMW,...
Results.Velocity,...
Results.Reynolds,...
Results.PressureDropBar,...
Results.LMTD,...
Results.HeatTransferKW,...
Results.CSPI,...
Results.Status,...
Results.Recommendation);



Graphs(...
Results.MassFlow,...
Results.HoodFlow,...
Results.LanceFlow,...
Results.RingFlow,...
Results.Qhood,...
Results.Qlance,...
Results.Qring,...
Results.PumpHead,...
Results.PressureDropBar,...
Results.CSPI);