function Results = RunSimulation(...
Q_total,...
Q_hood,...
Q_lance,...
Q_ring,...
Cp,...
rho,...
T_supply,...
T_return,...
PumpPressure,...
g,...
eta,...
mu,...
D,...
L,...
f,...
HotIn,...
HotOut,...
U,...
A)

%%================ MASS BALANCE ===========================

[MassFlow,HoodFlow,LanceFlow,RingFlow] = ...
MassBalance(Q_total,Q_hood,Q_lance,Q_ring,rho);

%%================ ENERGY BALANCE =========================

[Qhood,Qlance,Qring,Qtotal,DeltaT] = ...
EnergyBalance(HoodFlow,LanceFlow,RingFlow,...
Cp,T_supply,T_return);

%%================ PUMP MODEL =============================

[PressurePa,PumpHead,HydraulicPower,PumpPowerMW] = ...
PumpModel(PumpPressure,Q_total,rho,g,eta);

%%================ PRESSURE DROP ==========================

[Velocity,...
Area,...
Reynolds,...
DeltaP,...
PressureDropBar] = ...
PressureDrop(...
Q_total,...
rho,...
mu,...
D,...
L,...
f);

%%================ HEAT EXCHANGER =========================

[DeltaT1,...
DeltaT2,...
LMTD,...
HeatTransfer,...
HeatTransferKW] = ...
HeatExchanger(...
HotIn,...
HotOut,...
T_supply,...
T_return,...
U,...
A);

%%================ CSPI ==================================

[CSPIValue,...
Status,...
Recommendation] = ...
CSPI(...
Qtotal,...
PumpPowerMW);

%%================ STORE RESULTS ==========================

Results.MassFlow = MassFlow;
Results.HoodFlow = HoodFlow;
Results.LanceFlow = LanceFlow;
Results.RingFlow = RingFlow;

Results.Qhood = Qhood;
Results.Qlance = Qlance;
Results.Qring = Qring;
Results.Qtotal = Qtotal;
Results.DeltaT = DeltaT;

Results.PressurePa = PressurePa;
Results.PumpHead = PumpHead;
Results.HydraulicPower = HydraulicPower;
Results.PumpPowerMW = PumpPowerMW;

Results.Velocity = Velocity;
Results.Area = Area;
Results.Reynolds = Reynolds;
Results.DeltaP = DeltaP;
Results.PressureDropBar = PressureDropBar;

Results.DeltaT1 = DeltaT1;
Results.DeltaT2 = DeltaT2;
Results.LMTD = LMTD;
Results.HeatTransfer = HeatTransfer;
Results.HeatTransferKW = HeatTransferKW;

Results.CSPI = CSPIValue;
Results.Status = Status;
Results.Recommendation = Recommendation;

end